service: booking-tool

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-central-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:DescribeTable
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:BatchWriteItem
          Resource: 'arn:aws:dynamodb:eu-central-1:*:*'

functions:
  registerStudio:
    handler: src/functions/registerStudio.handler
    events:
      - cognitoUserPool:
          pool: tattooStudios
          trigger: PostConfirmation
          existing: true
  addTimeslot:
    handler: src/functions/addTimeslot.handler
    events:
      - http:
          path: timeslots/add
          method: post
          cors: true
  deleteTimeslot:
    handler: src/functions/deleteTimeslot.handler
    events:
      - http:
          path: timeslots/delete
          method: post
          cors: true
  deleteTimeslotSeries:
    handler: src/functions/deleteTimeslotSeries.handler
    events:
      - http:
          path: timeslots/delete-series
          method: post
          cors: true
  getTimeslots:
    handler: src/functions/getTimeslots.handler
    events:
      - http:
          path: timeslots/get
          method: get
          cors: true

plugins:
  - serverless-plugin-typescript
  - serverless-offline

resources:
  Resources:
    TattooStudioTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TattooStudio
        AttributeDefinitions:
          - AttributeName: studioID
            AttributeType: S
        KeySchema:
          - AttributeName: studioID
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    TattooerTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Tattooer
        AttributeDefinitions:
          - AttributeName: tattooerID
            AttributeType: S
        KeySchema:
          - AttributeName: tattooerID
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    TimeslotTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Timeslots
        AttributeDefinitions:
          - AttributeName: studioID
            AttributeType: S
          - AttributeName: timeslotID
            AttributeType: S
          - AttributeName: seriesID
            AttributeType: S
          - AttributeName: ttl
            AttributeType: N
        KeySchema:
          - AttributeName: studioID
            KeyType: HASH
          - AttributeName: timeslotID
            KeyType: RANGE
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: seriesIndex
            KeySchema:
              - AttributeName: seriesID
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
    NextAuthTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: next-auth
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
          - AttributeName: GSI1PK
            AttributeType: S
          - AttributeName: GSI1SK
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: GSI1
            Projection:
              ProjectionType: ALL
            KeySchema:
              - AttributeName: GSI1PK
                KeyType: HASH
              - AttributeName: GSI1SK
                KeyType: RANGE
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        TimeToLiveSpecification:
          AttributeName: expires
          Enabled: true
