service: booking-tool

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-central-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:DescribeTable
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:BatchWriteItem
          Resource: 'arn:aws:dynamodb:eu-central-1:*:*'

functions:
  registerStudio:
    handler: src/functions/registerStudio.handler
    events:
      - cognitoUserPool:
          pool: tattooStudios
          trigger: PostConfirmation
          existing: true
  updateStudio:
    handler: src/functions/updateStudio.handler
    events:
      - http:
          path: studio/update
          method: post
          cors: true
  addTimeslot:
    handler: src/functions/addTimeslot.handler
    events:
      - http:
          path: timeslots/add
          method: post
          cors: true
  deleteTimeslot:
    handler: src/functions/deleteTimeslot.handler
    events:
      - http:
          path: timeslots/delete
          method: post
          cors: true
  deleteTimeslotSeries:
    handler: src/functions/deleteTimeslotSeries.handler
    events:
      - http:
          path: timeslots/delete-series
          method: post
          cors: true
  getTimeslots:
    handler: src/functions/getTimeslots.handler
    events:
      - http:
          path: timeslots/get
          method: get
          cors: true
  getBookings:
    handler: src/functions/getBookingsByTattooer.handler
    events:
      - http:
          path: bookings/by-tattooer/get
          method: get
          cors: true
  getStudioByUrl:
    handler: src/functions/getStudioByUrl.handler
    events:
      - http:
          path: studio/by-url/get
          method: get
          cors: true
  getStudioByID:
    handler: src/functions/getStudioByID.handler
    events:
      - http:
          path: studio/by-id/get
          method: get
          cors: true
  sendBookingRequest:
    handler: src/functions/sendBookingRequest.handler
    events:
      - http:
          path: bookings/add
          method: post
          cors: true
  updateBookingRequest:
    handler: src/functions/updateBookingRequest.handler
    events:
      - http:
          path: bookings/update
          method: post
          cors: true

plugins:
  - serverless-plugin-typescript
  - serverless-offline

resources:
  Resources:
    TattooStudioTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TattooStudio
        AttributeDefinitions:
          - AttributeName: studioUrl
            AttributeType: S
          - AttributeName: studioID
            AttributeType: S
        KeySchema:
          - AttributeName: studioID
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: studioUrlIndex
            KeySchema:
              - AttributeName: studioUrl
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
    TattooerTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Tattooer
        AttributeDefinitions:
          - AttributeName: tattooerID
            AttributeType: S
          - AttributeName: studioID
            AttributeType: S
        KeySchema:
          - AttributeName: tattooerID
            KeyType: HASH
          - AttributeName: studioID
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    #     GlobalSecondaryIndexes:
    #       - IndexName: tattooerIndex
    #         KeySchema:
    #           - AttributeName: tattooerID
    #             KeyType: HASH
    #         Projection:
    #           ProjectionType: ALL
    #         ProvisionedThroughput:
    #           ReadCapacityUnits: 1
    #           WriteCapacityUnits: 1
    TimeslotTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Timeslots
        AttributeDefinitions:
          - AttributeName: studioID
            AttributeType: S
          # - AttributeName: tattooerID
          #   AttributeType: S
          - AttributeName: timeslotID
            AttributeType: S
          - AttributeName: seriesID
            AttributeType: S
          - AttributeName: ttl
            AttributeType: N
        KeySchema:
          - AttributeName: studioID
            KeyType: HASH
          - AttributeName: timeslotID
            KeyType: RANGE
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: seriesIndex
            KeySchema:
              - AttributeName: seriesID
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
    BookingTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Bookings
        AttributeDefinitions:
          - AttributeName: bookingID
            AttributeType: S
          - AttributeName: tattooerID
            AttributeType: S
          - AttributeName: status
            AttributeType: S
        KeySchema:
          - AttributeName: bookingID
            KeyType: HASH
          - AttributeName: tattooerID
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: tattooerIndex
            KeySchema:
              - AttributeName: tattooerID
                KeyType: HASH
              - AttributeName: status
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
    NextAuthTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: next-auth
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
          - AttributeName: GSI1PK
            AttributeType: S
          - AttributeName: GSI1SK
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: GSI1
            Projection:
              ProjectionType: ALL
            KeySchema:
              - AttributeName: GSI1PK
                KeyType: HASH
              - AttributeName: GSI1SK
                KeyType: RANGE
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        TimeToLiveSpecification:
          AttributeName: expires
          Enabled: true
